print("welcome to your easy calculator ^^)")
print("-"*35) 
num1=float(input("the first number :"))
num2=float(input("the second number :"))
print("the sum :"+str(num1+num2)) 
print("the subtract :"+str(num1-num2)) 
print("the multiply:"+str(num1*num2)) 
print("the divide :"+str(num1/num2)) 
print("the remainder:"+str(num1%num2)) 
print("perfect calculation") 
print("-"*35)
