# it's a code including informations about a hacker
name="witcher"
age=19
resultes=84.06
print(name.upper())
print(type(name))
print(type(age))
print(type(resultes))
print("hello "  + name)
print("the age is" + str(age))
print("\'witcher\'")
print(5%5)
print(10%5)
print(5%10)
print("تنين\n فاجر")
print("$")
print("$$")
print("$$$")
print("$$$$")
print("$$$$$")
print("$$$$$$")
print(5*6)
print(7+3)
print(7-3)
print(30/6)
print("fucker")
name=input("enter your name : ")
print("what a comeback !!"+name)

age=input("how old are u?")
print("your age is "+age)
name=input("enter your name sweet girl :")
print("witcher loves you sweet "+name)
price=input("how much?")
print("your total is "+price)
